openapi: 3.0.0
info:
  title: Swagger Petstore
  description: A sample API that stores information about pets
  version: 1.0.0

servers:
  - url: https://api.petstore.com/v1
    description: Production server
  - url: https://sandbox.petstore.com/v1
    description: Sandbox server

paths:
  /pets:
    get:
      summary: List all pets
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
    post:
      summary: Create a pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '201':
          description: Pet created

  /pets/{petId}:
    get:
      summary: Get a pet by ID
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single pet
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    Pet:
      type: object
      description: A pet available in the store
      properties:
        id:
          type: integer
          description: Unique identifier for the pet
        name:
          type: string
          description: Name of the pet
        status:
          type: string
          description: Pet status in the store
          enum: [available, pending, sold]

security:
  - ApiKeyAuth: []
